# Generated by Django 2.2.5 on 2021-12-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_movies', '0002_auto_20211216_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedmovies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie_Collected'),
        ),
        migrations.AlterField(
            model_name='moviecomments',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie_Collected'),
        ),
        migrations.AlterField(
            model_name='watchedmovies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie_Collected'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie_Collected'),
        ),
    ]
