# Generated by Django 2.2.5 on 2021-12-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Collected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('imdb_id', models.CharField(max_length=50, unique=True)),
                ('original_title', models.CharField(max_length=255)),
                ('original_language', models.CharField(max_length=255)),
                ('overview', models.TextField(null=True)),
                ('genres', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('poster_path', models.CharField(max_length=255, null=True)),
                ('production_company_name', models.CharField(max_length=255, null=True)),
                ('production_company_poster', models.CharField(max_length=255, null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('revenue', models.IntegerField(null=True)),
                ('release_date', models.CharField(max_length=20, null=True)),
                ('adult', models.BooleanField(null=True)),
                ('budget', models.IntegerField(null=True)),
                ('spoken_languages', models.TextField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('runtime', models.IntegerField(null=True)),
            ],
        ),
    ]
