# Generated by Django 2.2.5 on 2021-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_collected',
            name='original_language',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie_collected',
            name='original_title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie_collected',
            name='poster_path',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie_collected',
            name='production_company_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie_collected',
            name='production_company_poster',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie_collected',
            name='release_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie_collected',
            name='status',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
