# Generated by Django 2.2.5 on 2021-12-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211212_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_collected',
            name='budget',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie_collected',
            name='revenue',
            field=models.BigIntegerField(null=True),
        ),
    ]
