# Generated by Django 2.2.5 on 2021-12-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211212_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original_Movies_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=1000)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('ratings', models.FloatField(null=True)),
                ('poster_path', models.CharField(max_length=1000, null=True)),
                ('production_company_name', models.CharField(max_length=1000, null=True)),
                ('production_company_poster', models.CharField(max_length=1000, null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('revenue', models.BigIntegerField(null=True)),
                ('budget', models.BigIntegerField(null=True)),
                ('release_date', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=50, null=True)),
                ('cast', models.TextField(null=True)),
                ('crew', models.TextField(null=True)),
                ('director', models.CharField(max_length=1000, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Original_Movies_Table')),
            ],
        ),
    ]
